# Pytorch Fundamentals

In [ ]:
print("Hello I'm excited to learn Pytorch!")

Hello I'm excited to learn Pytorch!


In [ ]:
import torch
print(torch.__version__)

2.2.1+cu121


## Introduction to Tensors

### Creating Tensors

In [ ]:
#Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
##Get tensor back as Python int
scalar.item()


7

In [ ]:
vector=torch.tensor([7,7])

In [ ]:
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
MATRIX=torch.tensor([[5,5],[2,2],[3,3]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([3, 2])

In [ ]:
##Tensor
TENSOR=torch.tensor([[[1,2,3]],[[3,4,3]],[[5,6,7]],[[7,8,9]]])
TENSOR

tensor([[[1, 2, 3]],

        [[3, 4, 3]],

        [[5, 6, 7]],

        [[7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([4, 1, 3])

In [ ]:
TENSOR[3]

tensor([[7, 8, 9]])

## Random Tensors

In [ ]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.8943, 0.2244, 0.0383, 0.4118],
        [0.8223, 0.0640, 0.1432, 0.8064],
        [0.2320, 0.5822, 0.8530, 0.2143]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor[0]

tensor([0.8943, 0.2244, 0.0383, 0.4118])

In [ ]:
random_image_size_tensor=torch.rand(size=(3,224,224)) ##height,width,color channels

In [ ]:
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

**Zeros and Ones**


In [ ]:
zeros=torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones=torch.ones((3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

# **Creating a range of tensors and tensors-like**

In [ ]:
one_to_ten= torch.arange(0,100,2)
one_to_ten

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
        36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70,
        72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [ ]:
##creating tensors like
ten_zeros=torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])

## **Dealing with Tensor Data Type**

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=torch.float32,
                            device=None, ## What device is your tensor on
                               requires_grad=False) ## whether or not to track gradients
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [ ]:
float_32_tensor*float_16_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor=torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
int_32_tensor=float_32_tensor.type(torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

## Getting Information from Tensors
1. Tensors not right datatype - to do get datatype from a tensor, can use tensor.dtype
2.Tensors not right shape - to get shape from a tensor, can use tensor.shape
3. Tensors not on the right device - to get device from a tensor, can use tensor.device

In [ ]:
## Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.3785, 0.9330, 0.4071, 0.1726],
        [0.3746, 0.6500, 0.0037, 0.2422],
        [0.6495, 0.6978, 0.5999, 0.6919]])

In [ ]:
## Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.size()}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.3785, 0.9330, 0.4071, 0.1726],
        [0.3746, 0.6500, 0.0037, 0.2422],
        [0.6495, 0.6978, 0.5999, 0.6919]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### **Manipulating Tensors**



*   Addition
*   Substraction
*   Multiplication (element-wise)
*   Division
*   Matrix multiplication







In [ ]:
# Create tensor and add 10 to it
tensor=torch.tensor([[5,6,8],[11,12,13]])
tensor+10

tensor([[15, 16, 18],
        [21, 22, 23]])

In [ ]:
# Multiply tensor by 10
tensor*10

tensor([[ 50,  60,  80],
        [110, 120, 130]])

In [ ]:
## substract 10
tensor -10


tensor([[-5, -4, -2],
        [ 1,  2,  3]])

In [ ]:
## Try out PyTorch in-built functions
torch.mul(tensor,10)

tensor([[ 50,  60,  80],
        [110, 120, 130]])

## **Matrix Multiplication**



1.   Element wise multiplication
2.   Dot product



In [ ]:
# Element wise multiplication
print(tensor, "*", tensor)
print(tensor*tensor)

tensor([[ 5,  6,  8],
        [11, 12, 13]]) * tensor([[ 5,  6,  8],
        [11, 12, 13]])
tensor([[ 25,  36,  64],
        [121, 144, 169]])


In [ ]:
tensor=torch.tensor([1,2,3])

In [ ]:
# Create tensor and add 10 to it
tensor=torch.tensor([[5,6,8],[11,12,13]])


In [ ]:
torch.matmul(tensor,tensor.T)

tensor([[125, 231],
        [231, 434]])

In [ ]:
%%time
value=0
for i in range(len(tensor)):
  value+=(tensor[i]*tensor[i])
print(value)


tensor([146, 180, 233])
CPU times: user 1.85 ms, sys: 0 ns, total: 1.85 ms
Wall time: 3.58 ms


In [ ]:
%%time
torch.matmul(tensor,tensor)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

## **Dealing with shape errors in matrix multiplication**

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = tensor_A+6
print(tensor_A)
print(tensor_B)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])


In [ ]:
torch.matmul(tensor_A,tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

## **Min, Max and Sum**

In [ ]:
## create a tensor
x=torch.arange(1,100,10)


In [ ]:
#3 Find the position in tensor that has the minimum values with argmin() -> returns index position of target tesor where the minimum value occurs
x.argmin(0)

tensor(0)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
## find min
torch.min(x)

tensor(1)

In [ ]:
## find max
torch.max(x)

tensor(91)

In [ ]:
## find sum
torch.sum(x), sum(x)

(tensor(460), tensor(460))

In [ ]:
## find mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

### Reshaping,Stacking, Squeezing and Unsqueezing tensors
##Reshaping, Viewing and Stacking Tensors

In [ ]:
#   LET'S CREATE A TENSOR
x=torch.arange(1.0,10.)
x,x.shape,x.ndim

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), 1)

In [ ]:
## Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape,x_reshaped.ndim

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]), 2)

In [ ]:
#Change the view
##changing z changes x (because a view of a tensor shares the same momory as the original input)
z= x.view(1,9)
z,z.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
z[:,0]=5
x,z,z.ndim,x.ndim

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 2,
 1)

In [ ]:
##Stack tensors on top of each other
x_stacked =torch.stack([z,x_reshaped],dim=1)
x_stacked


tensor([[[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]])

In [ ]:
## torch.squeeze() - remove all single dimensions from a target tensor
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_reshaped.ndim

2

In [ ]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_reshaped.squeeze().ndim

1

In [ ]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

##Remove extra dimensions from x_reshaped
x_squeezed=x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
##torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim
print(f"Previous target: {x_squeezed}")
print(f"Previoys shape: {x_squeezed.shape}")


##Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New Shape: {x_unsqueezed.shape}")


Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previoys shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New Shape: torch.Size([1, 9])


In [ ]:
##torch.permute -reaarranges the dimensions of a target tensor in specified order
x_original = torch.rand(size=(224,224,3)) #height,width,colour_channels

##permute the original tensor to rearrange the axis (or dim) order
x_permuted =x_original.permute(2,0,1) ##shifts axis 0->1,1->2,2->0

x_original,x_permuted

(tensor([[[0.4962, 0.2460, 0.2416],
          [0.1668, 0.1756, 0.4932],
          [0.4025, 0.0364, 0.6766],
          ...,
          [0.6165, 0.3115, 0.9693],
          [0.9598, 0.9572, 0.0949],
          [0.6870, 0.6809, 0.3987]],
 
         [[0.0454, 0.6167, 0.2943],
          [0.9086, 0.9989, 0.3399],
          [0.3170, 0.0623, 0.8815],
          ...,
          [0.2173, 0.6284, 0.0954],
          [0.9029, 0.7777, 0.4977],
          [0.9865, 0.7920, 0.6374]],
 
         [[0.1308, 0.1603, 0.6073],
          [0.5413, 0.3978, 0.4490],
          [0.2659, 0.7437, 0.9748],
          ...,
          [0.5466, 0.4807, 0.0467],
          [0.3834, 0.7811, 0.8732],
          [0.6185, 0.3295, 0.4995]],
 
         ...,
 
         [[0.6250, 0.3965, 0.5631],
          [0.5122, 0.8210, 0.5471],
          [0.0592, 0.3594, 0.1825],
          ...,
          [0.6956, 0.4090, 0.8753],
          [0.0644, 0.4599, 0.7161],
          [0.6428, 0.1865, 0.8724]],
 
         [[0.1206, 0.0065, 0.9028],
          [0

In [ ]:
tryy=torch.rand(3,3,3)
print(tryy)
tryy1=tryy.permute(2,0,1)
print(tryy1)

tensor([[[0.1578, 0.0833, 0.9852],
         [0.4513, 0.1335, 0.8880],
         [0.7084, 0.0669, 0.5376]],

        [[0.9856, 0.8560, 0.3685],
         [0.1036, 0.1279, 0.2575],
         [0.2131, 0.2295, 0.0562]],

        [[0.5330, 0.7886, 0.4882],
         [0.0485, 0.5520, 0.2909],
         [0.7134, 0.9236, 0.1009]]])
tensor([[[0.1578, 0.4513, 0.7084],
         [0.9856, 0.1036, 0.2131],
         [0.5330, 0.0485, 0.7134]],

        [[0.0833, 0.1335, 0.0669],
         [0.8560, 0.1279, 0.2295],
         [0.7886, 0.5520, 0.9236]],

        [[0.9852, 0.8880, 0.5376],
         [0.3685, 0.2575, 0.0562],
         [0.4882, 0.2909, 0.1009]]])


In [ ]:
tryy1[2]

tensor([[0.9852, 0.8880, 0.5376],
        [0.3685, 0.2575, 0.0562],
        [0.4882, 0.2909, 0.1009]])

In [ ]:
tryy[0]

tensor([[0.1578, 0.0833, 0.9852],
        [0.4513, 0.1335, 0.8880],
        [0.7084, 0.0669, 0.5376]])

## Indexing (selecting from tensors)

In [ ]:
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
##Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
##Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
##Let's index on the most inner bracket (last dimension)
x[0][0][2]

tensor(3)

In [ ]:
##You can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
## Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
##Get all values of the 0 dimension but only the 1 index value of the 1st and 2 dimension
x[:,1,1]

tensor([5])

In [ ]:
## Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
##Index on x to return 9
print(x[0,2,2])

## index on x to return 3,6,9
print(x[0,:,2])

tensor(9)
tensor([3, 6, 9])


#Pytorch, Tensors and Numpy

##### **Data in Numpy, want in PyTorch tensor -> torch.from_numpy(ndarray)**
##### ***Pytorch tensor -> Numpy -> torch.Tensor.numpy() ***

In [ ]:
##Numpy array to tensor
import torch
import numpy as np

array= np.arange(1.0,8.0)
tensor=torch.from_numpy(array)
array,tensor


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
## Tensor to Numpy array
tensor = torch.ones(7)
tensor_to_numpy=tensor.numpy()
tensor,tensor_to_numpy

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (Trying to take random out of random)

In [ ]:
##create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)

print(random_tensor_A==random_tensor_B)

tensor([[0.3703, 0.8571, 0.6646, 0.9934],
        [0.4375, 0.9219, 0.4108, 0.3010],
        [0.1916, 0.7156, 0.9316, 0.8493]])
tensor([[0.9774, 0.8670, 0.9848, 0.0130],
        [0.8806, 0.2046, 0.3600, 0.6634],
        [0.9207, 0.7845, 0.0283, 0.0141]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
##set random seeds
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3,4)


torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)

print(random_tensor_A==random_tensor_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
!nvidia-smi

Sat Apr  6 21:50:43 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   42C    P8              12W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
torch.cuda.is_available()

True

In [ ]:
##setup device agnostic code


In [ ]:
torch.cuda.device_count()

1